obj-$(CONFIG_OMAP2_DSS) += omap-dss.o
omap-dss-y := dss.o display.o dispc.o dpi.o
omap-dss-$(CONFIG_OMAP2_DSS_RFBI) += rfbi.o
omap-dss-$(CONFIG_OMAP2_DSS_VENC) += venc.o
omap-dss-$(CONFIG_OMAP2_DSS_SDI) += sdi.o
omap-dss-$(CONFIG_OMAP2_DSS_DSI) += dsi.o
